cache:
  untracked: true
  key: '$CI_BUILD_REF_NAME'
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master
  tags:
    - build

deploy:
  stage: deploy
  script:
    - source ./env/production.sh
    - pm2 start --exp-backoff-restart-delay=200
  only:
    - master
  tags:
    - deploy
